version: '3.8'
services:
  frontend:
    networks:
      - my-network
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"

  backend:
    networks:
      - my-network
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"

networks:
  my-network:
    driver: bridge