name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/backend:latest -f backend/backend.Dockerfile backend
    - name: Build frontend
      run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/frontend:latest -f frontend/frontend.Dockerfile frontend
    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Push backend
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/backend:latest
    - name: Push frontend 
      run: docker push "${{ secrets.DOCKER_USERNAME }}"/frontend:latest
